version: "3.8"
services:
  postgres:
    image: postgres:latest
    env_file:
      - docker.env
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    image: matheussantos/chefchefe:latest
    container_name: chefchefe-web
    build:
      context: .
      target: production
    env_file:
      - docker.env
    ports:
      - "8001:8000"
    volumes:
      - ./src:/srv:delegated
    command: >
      sh -c "
      python manage.py migrate &&
      uvicorn chefchefe.asgi:application
      --host 0.0.0.0
      --port 8000
      --reload
      "
    depends_on:
      - postgres
      
volumes:
  postgres_data: