# Generated by Django 6.0.3 on 2026-03-27 04:42

import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('restaurant', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('identification', models.CharField(max_length=255, verbose_name='identificação')),
                ('is_open', models.BooleanField(default=False, verbose_name='aberto')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor inicial')),
                ('opened_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='aberto por')),
                ('closed_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='fechado por')),
                ('final_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor final')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers_closed', to='restaurant.employee')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers_opened', to='restaurant.employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'caixa',
                'verbose_name_plural': 'caixas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('method', models.CharField(choices=[('PERCENTAGE', 'Porcentagem'), ('VALUE', 'Valor'), ('VALUE_VARIABLE', 'Valor Variável'), ('PERCENTAGE_VARIABLE', 'Porcentagem Variável')], default='VALUE', max_length=20, verbose_name='método')),
                ('min_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor mínimo')),
                ('max_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor máximo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='restaurant.restaurant')),
                ('users_allowed', models.ManyToManyField(blank=True, help_text='Funcionários que podem usar este código de desconto. Se vazio, todos os funcionários podem usar.', related_name='discount_codes_allowed', to='restaurant.employee')),
            ],
            options={
                'verbose_name': 'código de desconto',
                'verbose_name_plural': 'códigos de desconto',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('CREDIT_CARD', 'Cartão de Crédito'), ('DEBIT_CARD', 'Cartão de Débito'), ('PIX', 'PIX'), ('CASH', 'Dinheiro'), ('OTHER', 'Outro')], default='CASH', max_length=20, verbose_name='método')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição')),
                ('postition', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'método de pagamento',
                'verbose_name_plural': 'métodos de pagamento',
                'ordering': ['postition', 'method'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='status changed')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='desconto')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('discount_code_code', models.CharField(blank=True, default='', max_length=50, verbose_name='código do desconto')),
                ('discount_used_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='desconto usado por')),
                ('client_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='nome do cliente')),
                ('client_cpf', localflavor.br.models.BRCPFField(blank=True, default=None, max_length=14, null=True, verbose_name='cpf do cliente')),
                ('client_cnpj', localflavor.br.models.BRCNPJField(blank=True, default=None, max_length=18, null=True, verbose_name='cnpj do cliente')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='BR', verbose_name='telefone do cliente')),
                ('tip_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor da gorjeta')),
                ('tip_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='porcentagem da gorjeta')),
                ('canceled_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='cancelado por')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_canceled', to='restaurant.employee')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='financial.cashier')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.customer')),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='financial.discountcode')),
                ('discount_used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_with_discount_used', to='restaurant.employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição')),
                ('method_description', models.CharField(blank=True, default='', max_length=255, verbose_name='descrição do método')),
                ('received_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor recebido')),
                ('exchange', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='troco')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída'), ('CANCELED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='status changed')),
                ('canceled_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='cancelado por')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_canceled', to='restaurant.employee')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.cashier')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.paymentmethod')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.sale')),
            ],
            options={
                'verbose_name': 'transação',
                'verbose_name_plural': 'transações',
                'ordering': ['-created'],
            },
        ),
    ]
