# Generated by Django 6.0.3 on 2026-03-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('restaurant', '0004_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='limit',
            field=models.PositiveIntegerField(default=0, help_text='Quantas vezes este código pode ser usado. Deixe 0 para ilimitado.', verbose_name='limite de uso'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='usado'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='código'),
        ),
        migrations.AlterUniqueTogether(
            name='discountcode',
            unique_together={('code', 'restaurant')},
        ),
    ]
