# Generated by Django 6.0.3 on 2026-05-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_discountcode_limit_discountcode_used_count_and_more'),
        ('restaurant', '0005_employee_can_close_cashier_employee_can_open_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
