# Generated by Django 6.0.3 on 2026-05-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_transaction_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['position', 'method'], 'verbose_name': 'método de pagamento', 'verbose_name_plural': 'métodos de pagamento'},
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='postition',
            new_name='position',
        ),
    ]
