# Generated by Django 6.0.3 on 2026-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_paymentmethod_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='received_value',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total',
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='troco'),
        ),
        migrations.AddField(
            model_name='sale',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor recebido'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SALE', 'Venda'), ('EXCHANGE', 'Troco'), ('SANGRIA', 'Sangria')], default='SALE', max_length=20, verbose_name='tipo'),
        ),
    ]
