# Generated by Django 6.0.3 on 2026-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_transaction_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='number_id',
            field=models.PositiveIntegerField(default=0, verbose_name='número'),
        ),
    ]
