# Generated by Django 6.0.3 on 2026-05-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_sale_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='saldo'),
        ),
    ]
