# Generated by Django 6.0.3 on 2026-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_sale_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SALE', 'Venda'), ('EXCHANGE', 'Troco'), ('SANGRIA', 'Sangria'), ('SUPPLY', 'Suprimento'), ('OTHER', 'Outro')], default='SALE', max_length=20, verbose_name='tipo'),
        ),
    ]
