# Generated by Django 6.0.3 on 2026-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='stats_url',
            field=models.URLField(blank=True, default='', verbose_name='url das estatísticas'),
        ),
    ]
