# Generated by Django 6.0.3 on 2026-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_cashier_stats_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='last_counter_bill_number',
            field=models.PositiveIntegerField(default=0, verbose_name='último número de comanda balcao'),
        ),
    ]
