# Generated by Django 6.0.3 on 2026-03-26 22:28

import apps.restaurant.models
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('is_admin', models.BooleanField(default=False, verbose_name='é administrador')),
                ('can_delete_item', models.BooleanField(default=False, verbose_name='pode excluir item')),
                ('can_delete_bill', models.BooleanField(default=False, verbose_name='pode excluir conta')),
                ('can_transfer_order', models.BooleanField(default=False, verbose_name='pode transferir pedido')),
                ('can_change_payment', models.BooleanField(default=False, verbose_name='pode alterar pagamento')),
                ('can_open_cashier', models.BooleanField(default=False, verbose_name='pode abrir caixa')),
                ('can_login_on_desktop', models.BooleanField(default=False, verbose_name='pode fazer login no desktop')),
                ('office', models.CharField(blank=True, default='', max_length=255, verbose_name='cargo')),
                ('sallary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='salário')),
                ('payment_day', models.PositiveIntegerField(default=0, verbose_name='dia de pagamento')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=255, verbose_name='bairro')),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, default='', max_length=9, verbose_name='cep')),
            ],
            options={
                'verbose_name': 'funcionário',
                'verbose_name_plural': 'funcionários',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NumberIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=255, unique=True, verbose_name='name')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Ultimo ID',
                'verbose_name_plural': 'Ultimos IDs',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('cicle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=11, verbose_name='ciclo')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor')),
                ('listed', models.BooleanField(default=True, verbose_name='listado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('days_trial', models.PositiveIntegerField(default=0, verbose_name='dias de teste')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('font_size', models.PositiveIntegerField(default=12, verbose_name='tamanho da fonte')),
                ('title_font_size', models.PositiveIntegerField(default=16, verbose_name='tamanho da fonte do título')),
                ('paper_size', models.PositiveBigIntegerField(default=80, help_text='mm', verbose_name='tamanho do papel')),
            ],
            options={
                'verbose_name': 'impressora',
                'verbose_name_plural': 'impressoras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='BR', verbose_name='telefone')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(blank=True, default='', max_length=9, verbose_name='cep')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='endereço')),
                ('address_number', models.CharField(blank=True, default='', max_length=10, verbose_name='número')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=255, verbose_name='bairro')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='cidade')),
                ('state', localflavor.br.models.BRStateField(blank=True, default='', max_length=2, verbose_name='estado')),
                ('complement', models.CharField(blank=True, default='', max_length=255, verbose_name='complemento')),
                ('token', models.CharField(db_index=True, default=apps.restaurant.models.generate_token, max_length=8, unique=True, verbose_name='token')),
                ('default_tip_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='valor padrão da gorjeta')),
                ('tip_aplyed_by_default', models.BooleanField(default=False, verbose_name='gorjeta aplicada por padrão')),
                ('tip_type', models.CharField(choices=[('percentage', 'Porcentagem'), ('value', 'Valor')], default='percentage', max_length=10, verbose_name='tipo da gorjeta')),
                ('cashier_default_initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor inicial padrão do caixa')),
                ('status', models.CharField(choices=[('TESTING', 'Teste'), ('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('CANCELLED', 'Cancelado')], default='TESTING', max_length=10, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('trial_ends', models.DateField(blank=True, null=True, verbose_name='fim do período de teste')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Cartão de Crédito'), ('PIX', 'PIX')], default='CREDIT_CARD', max_length=11, verbose_name='tipo de cobrança')),
                ('plan_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='valor do plano')),
                ('plan_cicle', models.CharField(choices=[('MONTHLY', 'Mensal'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=11, verbose_name='ciclo do plano')),
                ('plan_start_date', models.DateTimeField(blank=True, null=True, verbose_name='data de início do plano')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('OWNER', 'Proprietário'), ('MANAGER', 'Gerente'), ('USER', 'Usuário')], default='USER', max_length=10, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'usuário do restaurante',
                'verbose_name_plural': 'usuários do restaurante',
                'ordering': ['-created'],
            },
        ),
    ]
