# Generated by Django 5.1.6 on 2025-04-09 03:34

import apps.restaurant.models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('cicle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=11, verbose_name='cicle')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='value')),
                ('listed', models.BooleanField(default=True, verbose_name='listed')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('days_trial', models.PositiveIntegerField(default=0, verbose_name='days trial')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plans',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('permission', models.CharField(max_length=255, unique=True, verbose_name='permission')),
                ('method', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], default='READ', max_length=10, verbose_name='method')),
            ],
            options={
                'verbose_name': 'user permission',
                'verbose_name_plural': 'users permissions',
                'ordering': ['permission'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[('TESTING', 'Testing'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('CANCELLED', 'Cancelled')], default='TESTING', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(blank=True, default='', max_length=255, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='BR', verbose_name='phone')),
                ('postal_code', localflavor.br.models.BRPostalCodeField(blank=True, default='', max_length=9, verbose_name='postal code')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='address')),
                ('address_number', models.CharField(blank=True, default='', max_length=10, verbose_name='address number')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=255, verbose_name='neighborhood')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='city')),
                ('state', localflavor.br.models.BRStateField(blank=True, default='', max_length=2, verbose_name='state')),
                ('complement', models.CharField(blank=True, default='', max_length=255, verbose_name='complement')),
                ('token', models.CharField(db_index=True, default=apps.restaurant.models.generate_token, max_length=8, unique=True, verbose_name='token')),
                ('default_tip_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='default tip value')),
                ('tip_aplyed_by_default', models.BooleanField(default=False, verbose_name='tip aplied by default')),
                ('tip_type', models.CharField(choices=[('percentage', 'Percentage'), ('value', 'Value')], default='percentage', max_length=10, verbose_name='tip type')),
                ('cashier_default_initial_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='cashier default initial value')),
                ('order_last_sequencial_number', models.PositiveIntegerField(default=0, verbose_name='order last sequencial number')),
                ('trial_ends_at', models.DateField(blank=True, null=True, verbose_name='trial ends at')),
                ('billing_type', models.CharField(choices=[('BOLETO', 'Boleto'), ('CREDIT_CARD', 'Credit Card'), ('PIX', 'PIX')], default='CREDIT_CARD', max_length=11, verbose_name='billing type')),
                ('plan_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='plan value')),
                ('plan_cicle', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=11, verbose_name='plan cicle')),
                ('plan_start_date', models.DateTimeField(blank=True, null=True, verbose_name='plan start date')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.plan', verbose_name='plan')),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('font_size', models.PositiveIntegerField(default=12, verbose_name='font size')),
                ('title_font_size', models.PositiveIntegerField(default=16, verbose_name='title font size')),
                ('paper_size', models.PositiveBigIntegerField(default=80, help_text='mm', verbose_name='paper size')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='restaurant.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'printer',
                'verbose_name_plural': 'printers',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is admin')),
                ('can_delete_item', models.BooleanField(default=False, verbose_name='can delete item')),
                ('can_delete_bill', models.BooleanField(default=False, verbose_name='can delete bill')),
                ('can_transfer_order', models.BooleanField(default=False, verbose_name='can transfer order')),
                ('can_change_payment', models.BooleanField(default=False, verbose_name='can change payment')),
                ('can_open_cashier', models.BooleanField(default=False, verbose_name='can open cashier')),
                ('can_login_on_desktop', models.BooleanField(default=False, verbose_name='can login on desktop')),
                ('office', models.CharField(blank=True, default='', max_length=255, verbose_name='office')),
                ('sallary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='sallary')),
                ('payment_day', models.PositiveIntegerField(default=0, verbose_name='payment day')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=255, verbose_name='neighborhood')),
                ('cep', localflavor.br.models.BRPostalCodeField(blank=True, default='', max_length=9, verbose_name='cep')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurant.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserRestaurant',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=10, verbose_name='role')),
                ('permission', models.ManyToManyField(blank=True, to='restaurant.userpermissions', verbose_name='permissions')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurants', to='restaurant.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'user restaurant',
                'verbose_name_plural': 'users restaurants',
                'ordering': ['-created'],
            },
        ),
    ]
