# Generated by Django 6.0.3 on 2026-03-26 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='proprietário'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurant.plan', verbose_name='plano'),
        ),
        migrations.AddField(
            model_name='printer',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='restaurant.restaurant', verbose_name='restaurante'),
        ),
        migrations.AddField(
            model_name='numberidcounter',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_id_counters', to='restaurant.restaurant', verbose_name='restaurant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurant.restaurant', verbose_name='restaurante'),
        ),
        migrations.AddField(
            model_name='userrestaurant',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurants', to='restaurant.restaurant', verbose_name='restaurante'),
        ),
        migrations.AddField(
            model_name='userrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('code', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
