# Generated by Django 5.1.6 on 2025-04-09 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together={('name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('code', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='userrestaurant',
            unique_together={('user', 'restaurant')},
        ),
    ]
