# Generated by Django 6.0.3 on 2026-03-27 04:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.PositiveIntegerField(verbose_name='número')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='título')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='capacidade')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant', verbose_name='restaurante')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['number'],
                'unique_together': {('number', 'restaurant')},
            },
        ),
    ]
