# Generated by Django 6.0.3 on 2026-03-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-created'], 'verbose_name': 'restaurante', 'verbose_name_plural': 'restaurantes'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_login_on_desktop',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_open_cashier',
        ),
        migrations.AlterField(
            model_name='employee',
            name='can_delete_bill',
            field=models.BooleanField(default=False, verbose_name='pode excluir comanda'),
        ),
        migrations.AlterField(
            model_name='numberidcounter',
            name='name',
            field=models.SlugField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='numberidcounter',
            unique_together={('name', 'restaurant')},
        ),
    ]
