# Generated by Django 6.0.3 on 2026-05-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_close_cashier',
            field=models.BooleanField(default=False, verbose_name='pode fechar caixa'),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_open_cashier',
            field=models.BooleanField(default=False, verbose_name='pode abrir caixa'),
        ),
    ]
