# Generated by Django 6.0.3 on 2026-05-13 15:10

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_employee_can_close_cashier_employee_can_open_cashier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payload', models.JSONField(verbose_name='payload')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SENT', 'Enviado'), ('ERROR', 'Erro')], default='PENDING', max_length=10, verbose_name='status')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='restaurant.printer', verbose_name='impressora')),
            ],
            options={
                'verbose_name': 'tarefa de impressão',
                'verbose_name_plural': 'tarefas de impressão',
                'ordering': ['-created'],
            },
        ),
    ]
