# Generated by Django 6.0.3 on 2026-05-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_printjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='restaurant.restaurant', verbose_name='restaurante'),
            preserve_default=False,
        ),
    ]
