# Generated by Django 6.0.3 on 2026-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_printjob_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_move_item',
            field=models.BooleanField(default=False, verbose_name='pode mover item'),
        ),
    ]
