# Generated by Django 6.0.3 on 2026-05-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_employee_can_move_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='can_move_item',
        ),
    ]
