# Generated by Django 6.0.3 on 2026-05-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_employee_can_move_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together=set(),
        ),
    ]
