# Generated by Django 6.0.3 on 2026-05-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_alter_printer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cashier_default_counter_bill_start',
            field=models.PositiveIntegerField(default=1, verbose_name='número inicial padrão das comandas do balcão'),
        ),
    ]
