# Generated by Django 6.0.3 on 2026-03-27 04:42

import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, default=None, max_length=14, null=True, verbose_name='cpf')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, default='', max_length=18, null=True, verbose_name='cnpj')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='BR', verbose_name='telefone')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created'],
            },
        ),
    ]
