# Generated by Django 6.0.3 on 2026-03-26 22:45

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_categories', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Complement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço')),
                ('max', models.PositiveIntegerField(default=1, verbose_name='max')),
                ('min', models.PositiveIntegerField(default=0, verbose_name='min')),
                ('tag', models.CharField(blank=True, default='', max_length=255, verbose_name='tag')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complements', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'complemento',
                'verbose_name_plural': 'complementos',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComplementGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('tag', models.CharField(blank=True, default='', max_length=255, verbose_name='tag')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('rule', models.CharField(choices=[('HIGH', 'Maior'), ('SUM', 'Soma'), ('MEDIAN', 'Mediana')], default='SUM', max_length=10, verbose_name='regra')),
                ('min', models.PositiveIntegerField(default=0, verbose_name='mínimo')),
                ('max', models.PositiveIntegerField(default=1, verbose_name='máximo')),
                ('complements', models.ManyToManyField(related_name='complement_groups', to='products.complement')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_groups', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'grupo de complementos',
                'verbose_name_plural': 'grupos de complementos',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('code', models.CharField(blank=True, default='', max_length=255, verbose_name='código')),
                ('sell_type', models.CharField(choices=[('UN', 'Unidade'), ('KG', 'Quilo')], default='UN', max_length=10, verbose_name='tipo de venda')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='restaurant.printer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductComplementGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('complement_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.complementgroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_groups', to='products.product')),
            ],
            options={
                'verbose_name': 'grupo de complementos do produto',
                'verbose_name_plural': 'grupos de complementos dos produtos',
                'ordering': ['position'],
            },
        ),
    ]
