# Generated by Django 6.0.3 on 2026-03-27 04:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('products', '0001_initial'),
        ('restaurant', '0003_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.PositiveIntegerField(default=0, verbose_name='número')),
                ('identification', models.CharField(blank=True, default='', max_length=255, verbose_name='identificação')),
                ('is_open', models.BooleanField(default=True, verbose_name='aberta')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='aberta em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechada em')),
                ('opened_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='aberta por')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_opened', to='restaurant.employee')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='restaurant.restaurant')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='financial.sale')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='restaurant.table')),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.PositiveIntegerField(default=0, verbose_name='número')),
                ('product_name', models.CharField(max_length=255, verbose_name='nome do produto')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço unitário')),
                ('complements_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço dos complementos')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em preparo'), ('READY', 'Pronto'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='status')),
                ('canceled_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='cancelada por')),
                ('launched_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='lançada por')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.bill')),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_canceled', to='restaurant.employee')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_launched', to='restaurant.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='products.product')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderComplement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('complement_name', models.CharField(max_length=255, verbose_name='nome do complemento')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='preço unitário')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço total')),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_complements', to='products.complement')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complements', to='products.order')),
            ],
            options={
                'verbose_name': 'complemento do pedido',
                'verbose_name_plural': 'complementos dos pedidos',
                'ordering': ['-created'],
            },
        ),
    ]
