# Generated by Django 6.0.3 on 2026-03-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bill_order_ordercomplement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementgroup',
            name='complements',
        ),
        migrations.AddField(
            model_name='complement',
            name='complement_group',
            field=models.ForeignKey(default='e9bf3bdd-34ba-4c6d-9155-98478635e31e', on_delete=django.db.models.deletion.CASCADE, related_name='complements', to='products.complementgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complementgroup',
            name='product',
            field=models.ForeignKey(default='ce41f226-2f97-4460-a63b-46b93fe59f96', on_delete=django.db.models.deletion.CASCADE, related_name='complement_groups', to='products.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductComplementGroup',
        ),
    ]
