# Generated by Django 6.0.3 on 2026-03-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_complementgroup_complements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='código'),
        ),
    ]
