# Generated by Django 6.0.3 on 2026-03-29 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slug_alter_product_code'),
        ('restaurant', '0004_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.bill'),
            preserve_default=False,
        ),
    ]
