# Generated by Django 6.0.3 on 2026-03-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_restaurant_alter_order_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='status alterado em'),
        ),
    ]
