# Generated by Django 6.0.3 on 2026-03-30 23:43

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_status_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=11, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_changed',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='status changed'),
        ),
    ]
