# Generated by Django 6.0.3 on 2026-04-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_order_quantity_alter_order_status_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complements_details',
            field=models.JSONField(blank=True, null=True, verbose_name='detalhes dos complementos'),
        ),
    ]
