# Generated by Django 6.0.3 on 2026-04-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_complements_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_notes',
            field=models.TextField(blank=True, default='', verbose_name='observações de cancelamento'),
        ),
    ]
