# Generated by Django 6.0.3 on 2026-05-08 12:33

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_cancel_notes'),
        ('restaurant', '0004_alter_restaurant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bills', models.ManyToManyField(related_name='bill_groups', to='products.bill')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_groups', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
