# Generated by Django 6.0.3 on 2026-05-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_billgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billgroup',
            name='bills',
            field=models.ManyToManyField(blank=True, related_name='bill_groups', to='products.bill'),
        ),
    ]
