# Generated by Django 6.0.3 on 2026-05-13 16:03

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_billgroup_bills'),
        ('restaurant', '0007_printjob_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='estoque'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_change',
            field=model_utils.fields.MonitorField(blank=True, default=None, monitor='stock', null=True, verbose_name='stock changed'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='quantidade')),
                ('notes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('processed', models.BooleanField(default=False, verbose_name='processado')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'movimentação de estoque',
                'verbose_name_plural': 'movimentações de estoque',
                'ordering': ['-created'],
            },
        ),
    ]
