# Generated by Django 6.0.3 on 2026-05-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_stock_product_stock_change_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_bills',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='últimas comanda'),
        ),
    ]
