# Generated by Django 6.0.3 on 2026-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_last_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='close_detail',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='detalhes do fechamento'),
        ),
    ]
