# Generated by Django 6.0.3 on 2026-05-15 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_transaction_type'),
        ('products', '0014_bill_close_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cashier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='financial.cashier'),
        ),
    ]
