# Generated by Django 6.0.3 on 2026-05-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_bill_cashier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='cashier_id',
            new_name='cashier',
        ),
    ]
